AppBundle\Entity\Quote:
    type:  entity
    table: quote
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        details:
            type: text
        price:
            type: float
        createdAt:
            type: date
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            gedmo:
                timestampable:
                   on: update